const { id } = require('../../commonCypress')
describe('user register', () => {
  it('shows the courses', () => {
    cy.request('http://localhost:3002/cookieBanner/OK')
    cy.visit('http://localhost:3002/users/new')
    cy.get('#inputFirstName')
      .type('Jonah')
      .should('have.value', 'Jonah')
    cy.get('#inputLastName')
      .type('Harting')
    cy.get('#inputPassword')
      .type('geheim12')
    cy.get('#inputEmail')
      .type(`len_zintl_${id()}@hotmail.com`)
    cy.get('#inputZipCode')
      .type(12321)
    cy.contains('Create a new user:')
    cy.get('#submitButton').click()
    cy.contains('Jonah')
  })
})
