env:
  browser: true
  es6: true
  node: true
  jest: true
  cypress/globals: true
extends:
  - 'plugin:react/recommended'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - cypress
settings:
  react:
    version: detect
rules: {
  "react/react-in-jsx-scope": "off",
}
