'use strict'

const modules = [{
  semester: 1,
  required: 'required',
  code: 'B1',
  name: 'Informatik  1',
  mission: null,
  ects: 4,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.706Z',
  updated_at: '2020-05-01T10:15:24.706Z'
}, {
  semester: 1,
  required: 'required',
  code: 'B2',
  name: 'Computersysteme',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.740Z',
  updated_at: '2020-05-01T10:15:24.740Z'
}, {
  semester: 1,
  required: 'required',
  code: 'B3',
  name: 'Propädeutikum und  Medientheorie',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.759Z',
  updated_at: '2020-05-01T10:15:24.759Z'
}, {
  semester: 1,
  required: 'required',
  code: 'B4',
  name: 'Mathematik  für Medieninformatik 1',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.779Z',
  updated_at: '2020-05-01T10:15:24.779Z'
}, {
  semester: 1,
  required: 'required',
  code: 'B5',
  name: 'Grundlagen  der  Webprogrammierung',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.797Z',
  updated_at: '2020-05-01T10:15:24.797Z'
}, {
  semester: 1,
  required: 'required',
  code: 'B6',
  name: '1.  Fremdsprache         1',
  mission: null,
  ects: 4,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'WP Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.816Z',
  updated_at: '2020-05-01T10:15:24.816Z'
}, {
  semester: 2,
  required: 'required',
  code: 'B7',
  name: 'Informatik 2',
  mission: null,
  ects: 4,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.843Z',
  updated_at: '2020-05-01T10:15:24.843Z'
}, {
  semester: 2,
  required: 'required',
  code: 'B8',
  name: 'Grundlagen Digitaler Medien',
  mission: null,
  ects: 4,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.862Z',
  updated_at: '2020-05-01T10:15:24.862Z'
}, {
  semester: 2,
  required: 'required',
  code: 'B9',
  name: 'Netzwerke',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.880Z',
  updated_at: '2020-05-01T10:15:24.880Z'
}, {
  semester: 2,
  required: 'required',
  code: 'B10',
  name: 'Mathematik für    Medieninformatik 2',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.898Z',
  updated_at: '2020-05-01T10:15:24.898Z'
}, {
  semester: 2,
  required: 'required',
  code: 'B11',
  name: 'Medienwirtschaft',
  mission: null,
  ects: 4,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.918Z',
  updated_at: '2020-05-01T10:15:24.918Z'
}, {
  semester: 2,
  required: 'required',
  code: 'B12',
  name: '1.  Fremdsprache',
  mission: null,
  ects: 0,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: '2 WP',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.940Z',
  updated_at: '2020-05-01T10:15:24.940Z'
}, {
  semester: 3,
  required: 'required',
  code: 'B13',
  name: 'Bildverarbeitung',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.957Z',
  updated_at: '2020-05-01T10:15:24.957Z'
}, {
  semester: 3,
  required: 'required',
  code: 'B14',
  name: 'Datenbanken',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.975Z',
  updated_at: '2020-05-01T10:15:24.975Z'
}, {
  semester: 3,
  required: 'required',
  code: 'B15',
  name: 'Informatik 3',
  mission: null,
  ects: 4,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:24.992Z',
  updated_at: '2020-05-01T10:15:24.992Z'
}, {
  semester: 3,
  required: 'required',
  code: 'B16',
  name: '2. Fremdsprache',
  mission: null,
  ects: 4,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'WP Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.018Z',
  updated_at: '2020-05-01T10:15:25.018Z'
}, {
  semester: 3,
  required: 'required',
  code: 'B17',
  name: 'Computergrafik',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.036Z',
  updated_at: '2020-05-01T10:15:25.036Z'
}, {
  semester: 3,
  required: 'required',
  code: 'B18',
  name: '3D-Design',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.054Z',
  updated_at: '2020-05-01T10:15:25.054Z'
}, {
  semester: 4,
  required: 'required',
  code: 'B19',
  name: 'Internationale   Medienwirtschaft  und  Kommunikation',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.071Z',
  updated_at: '2020-05-01T10:15:25.071Z'
}, {
  semester: 4,
  required: 'required',
  code: 'B20',
  name: 'Praxisphase 1:  Fachpraktikum im  Ausland',
  mission: null,
  ects: 25,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P ',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.088Z',
  updated_at: '2020-05-01T10:15:25.088Z'
}, {
  semester: 4,
  required: 'required',
  code: 'B20.1',
  name: 'Auswertung  von Erfahrungen am Praxisplatz',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'EL Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.104Z',
  updated_at: '2020-05-01T10:15:25.104Z'
}, {
  semester: 4,
  required: 'required',
  code: 'B20.2',
  name: 'Fachpraktikum',
  mission: null,
  ects: 25,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: ' ',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.126Z',
  updated_at: '2020-05-01T10:15:25.126Z'
}, {
  semester: 5,
  required: 'required',
  code: 'B21',
  name: 'Wahlpflichtmodul 1',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'WP SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.143Z',
  updated_at: '2020-05-01T10:15:25.143Z'
}, {
  semester: 5,
  required: 'required',
  code: 'B22',
  name: 'Wahlpflichtmodul 2',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'WP SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.160Z',
  updated_at: '2020-05-01T10:15:25.160Z'
}, {
  semester: 5,
  required: 'required',
  code: 'B23',
  name: 'Wahlpflichtmodul 3',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'WP SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.183Z',
  updated_at: '2020-05-01T10:15:25.183Z'
}, {
  semester: 5,
  required: 'required',
  code: 'B24.1',
  name: 'Praxisphase 2:Praxisprojekt',
  mission: null,
  ects: 15,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'WP 15',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.198Z',
  updated_at: '2020-05-01T10:15:25.198Z'
}, {
  semester: 5,
  required: 'required',
  code: 'B24.2',
  name: 'Projektmanagement',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: ' Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.215Z',
  updated_at: '2020-05-01T10:15:25.215Z'
}, {
  semester: 6,
  required: 'required',
  code: 'B25',
  name: 'Wahlpflichtmodul 4',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'WP SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.231Z',
  updated_at: '2020-05-01T10:15:25.231Z'
}, {
  semester: 6,
  required: 'required',
  code: 'B26',
  name: 'Wahlpflichtmodul 5',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'WP SL/Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.248Z',
  updated_at: '2020-05-01T10:15:25.248Z'
}, {
  semester: 6,
  required: 'required',
  code: 'B27',
  name: 'AWE:  Medienrecht',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P SL',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.264Z',
  updated_at: '2020-05-01T10:15:25.264Z'
}, {
  semester: 6,
  required: 'required',
  code: 'B28',
  name: 'AWE  WP',
  mission: null,
  ects: 2,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'SL ',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.280Z',
  updated_at: '2020-05-01T10:15:25.280Z'
}, {
  semester: 6,
  required: 'required',
  code: 'B29',
  name: 'Bachelorarbeit',
  mission: null,
  ects: 0,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P ',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.296Z',
  updated_at: '2020-05-01T10:15:25.296Z'
}, {
  semester: 6,
  required: 'required',
  code: 'B30',
  name: 'Bachelorseminar/Kolloquium',
  mission: null,
  ects: 1,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'P Ü',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.319Z',
  updated_at: '2020-05-01T10:15:25.319Z'
}, {
  semester: 0,
  required: 'elective',
  code: 'GTAT1',
  name: 'Game  Technology  \u0026  Interactive  Systems  – Aktuelle  Themen  1',
  mission: null,
  ects: 5,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'SL/Ü 2/2',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.336Z',
  updated_at: '2020-05-01T10:15:25.336Z'
}, {
  semester: 0,
  required: 'elective',
  code: 'VCAT1',
  name: 'Visual  Computing  –  Aktuelle Themen 1',
  mission: null,
  ects: 5,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'SL/Ü 2/2',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.354Z',
  updated_at: '2020-05-01T10:15:25.354Z'
}, {
  semester: 0,
  required: 'elective',
  code: 'WTAT1',
  name: 'Web Technology  –  Aktuelle Themen 1',
  mission: null,
  ects: 5,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'SL/Ü 2/2',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.371Z',
  updated_at: '2020-05-01T10:15:25.371Z'
}, {
  semester: 0,
  required: 'elective',
  code: 'GT2',
  name: 'Game  Engines',
  mission: null,
  ects: 5,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'SL/Ü 2/2',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.388Z',
  updated_at: '2020-05-01T10:15:25.388Z'
}, {
  semester: 0,
  required: 'elective',
  code: 'VC2',
  name: 'Bildanalyse',
  mission: null,
  ects: 5,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'SL/Ü 2/2',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.405Z',
  updated_at: '2020-05-01T10:15:25.405Z'
}, {
  semester: 0,
  required: 'elective',
  code: 'WT2',
  name: 'Usability',
  mission: null,
  ects: 5,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'SL/Ü 2/2',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.423Z',
  updated_at: '2020-05-01T10:15:25.423Z'
}, {
  semester: 0,
  required: 'elective',
  code: 'GTAT2',
  name: 'Game Technology \u0026 Interactive Systems – Aktuelle Themen 2',
  mission: null,
  ects: 5,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'SL/Ü 2/2',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.441Z',
  updated_at: '2020-05-01T10:15:25.441Z'
}, {
  semester: 0,
  required: 'elective',
  code: 'VCAT2',
  name: 'Visual  Computing – Aktuelle Themen 2',
  mission: null,
  ects: 5,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'SL/Ü 2/2',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.459Z',
  updated_at: '2020-05-01T10:15:25.459Z'
}, {
  semester: 0,
  required: 'elective',
  code: 'WTAT2',
  name: 'Web  Technology – Aktuelle Themen2',
  mission: null,
  ects: 5,
  examination: null,
  objectives: null,
  contents: null,
  prerequisites: null,
  literature: null,
  methods: 'SL/Ü 2/2',
  skills_knowledge_understanding: null,
  skills_intellectual: null,
  skills_practical: null,
  skills_general: null,
  created_at: '2020-05-01T10:15:25.483Z',
  updated_at: '2020-05-01T10:15:25.483Z'
}]

const studentProgress = [
  {
    code: 'B1',
    semester: 'WS2019/2020',
    status: 'passed'
  },
  {
    code: 'B2',
    semester: 'WS2019/2020',
    status: 'passed'
  },
  {
    code: 'B3',
    semester: 'WS2019/2020',
    status: 'passed'
  },
  {
    code: 'B4',
    semester: 'WS2019/2020',
    status: 'passed'
  },
  {
    code: 'B5',
    semester: 'WS2019/2020',
    status: 'enrolled'
  },

  {
    code: 'B6',
    semester: 'WS2019/2020',
    status: 'enrolled'
  },
  {
    code: 'B7',
    semester: 'SoSe 2020',
    status: 'enrolled'
  },
  {
    code: 'B8',
    semester: 'SoSe 2020',
    status: 'enrolled'
  },
  {
    code: 'B9',
    semester: 'SoSe 2020',
    status: 'enrolled'
  },
  {
    code: 'B10',
    semester: 'SoSe 2020',
    status: 'enrolled'
  },
  {
    code: 'B13',
    semester: 'WS2020/2021',
    status: 'planned'
  },
  {
    code: 'B14',
    semester: 'WS2020/2021',
    status: 'planned'
  },
  {
    code: 'B15',
    semester: 'WS2020/2021',
    status: 'planned'
  }

]
const defaultStudentProgress = {
  code: '',
  semester: '',
  status: 'none'
}

exports.showIndex = (req, res) => {
  res.render('index')
}
exports.showStudentView = (req, res) => {
  // console.log(req.params);
  // console.log(req.params.format);
  // console.log("path: " + req.path);
  // console.log("url: " + req.url);
  // console.log(req.route)
  const requestedView = req.params.format || 'list'
  // console.log(requestedView);
  const view = 'modules_' + requestedView
  res.render(view, {
    modules: modules,
    studentProgress: studentProgress,
    defaultStatus: defaultStudentProgress
  })
}
exports.showAbout = (req, res) => {
  res.render('about')
}
